function PlotMAPEHistogram( serieseval, imgpairlbl, ualg, uparamset, ueval, varargin )
%PLOTMAPEHISTOGRAM visualizes the MAPE distribution over all datasets
%Input:
%   <imgpaireval>      image pair series evaluation generated by <TFMSim3D.m>
%   <imgpairlbl>       image pair name
%   <ualg>             name of displacement calculation algorithm
%   <uparamset>        parameter set number for displacement calculation
%   <ueval>            name of displacement evaluation method
%   <Talg>             (optional) name of traction calculation algorithm
%   <Tparamset>        (optional) parameter set number for traction calculation
%   <Teval>            (optional) name of traction evaluation method
%CL

% Determine method
if ~isempty(varargin)
    % Use traction data
    method = 'T';
    Talg = varargin{1};
    Tparamset = varargin{2};
    Teval = varargin{3};
else
    % Use displacement data
    method = 'u';
end

% Get data
ndatasets = serieseval.ndatasets;
for j = 1:ndatasets
    if strcmp('T',method)
        MAPE(j) = nanmean(serieseval.T.(imgpairlbl).(ualg).(ueval){uparamset}.(Talg).(Teval){Tparamset}.data{j}.APE);
    else
        MAPE(j) = nanmean(serieseval.u.(imgpairlbl).(ualg).(ueval){uparamset}.data{j}.APE);
    end
end
meanMAPE = mean(MAPE);
medianMAPE = median(MAPE);

% Plot
figure
hold on
title({sprintf('MAPE distribution over the series of %d datasets',ndatasets);...
    sprintf('mean = %.3f %%, median = %.3f %%',meanMAPE,medianMAPE)})
hist(MAPE,20)
h1 = plot([meanMAPE,meanMAPE],ylim,'r--');
h2 = plot([medianMAPE,medianMAPE],ylim,'g--');
xlabel('MAPE [%]')
ylabel('Occurrence')
legend([h1,h2],'mean','median')

end

